### Задача 1

Из первого уравнения выразим:
$$I_s(g(2\rho_s-1)-1)=0\\
g(2\rho_s-1)-1=0\\
\rho_s=\frac{\frac{1}{g}+1}{2}$$

Из третьего уравнения:
$$\eta_w(J_{thr}-n_s-2F(\rho_s,n_s))=0 \Leftrightarrow n_s=\frac{J_{thr}}{1+2B(1-\rho_s)}$$

Из второго уравнения:
$$\eta_d(F(\rho_s,n_s)-\rho_s-I_s(2\rho_s-1))=0 \Leftrightarrow I_s=\frac{Bn_s(1-\rho_s)-\rho_s}{2\rho_s-1}$$

Подставляя полученные выше результаты для уравнений (1) и (3) в (2) и упрощая, получаем:

$$I_s=\frac{J_{thr}B(1-\rho_s)}{(2\rho_s-1)(2B(1-\rho_s)+1)}-\frac{\rho_s}{2\rho_s-1}$$

Обращаясь к условию $I_s>0$, можем использовать это выражение для расчета порогового параметра накачки и вернуться к расчету нормированного числа носителей заряда в смачивающем слое. Так получены следующие численные значения:

$$\rho_s=0.9273504273504274$$
$$n_s=0.01823529411764707222$$
$$J_{thr}=1.87293614881850187$$




### Задачи 2-3

Импорт необходимых библиотек

In [1]:
from scipy.integrate import solve_ivp
import matplotlib.pyplot as plt
import numpy as np
#import matplotlib as mpl
#mpl.use('webagg')

Определение системы

In [2]:
def odes(t,y,B,f_a):
    I, rho, n = y
    F=B*n*(1-rho)
    dydt=[I*(g*(2*rho-1)-1),
          eta_d*(F-rho-I*(2*rho-1)),
          eta_w*(J+delta_a*np.sin(2*np.pi*f_a*t)-n-2*F)]
    return dydt

Параметры

In [3]:
g=1.17
J=0.75*4*1.87293614881850187
B=700
tau_d=0.9*10**(-9)
tau_p=20*10**(-12)
tau_w=1*10**(-9)
eta_d=tau_p/tau_d
eta_w=tau_p/tau_w
delta_a=0.1*J

Во второй лабораторной работе значение частоты определено как $f_{ro}=2.39\text{ ГГц}$. Для перехода к нормированным единицам домножим на время жизни фотона в резонаторе:

In [4]:
f=2.39*10**9*tau_p
f_array=np.arange(0.05*f,1.25*f, (1.25*f-0.05*f)/20)

Получен массив из 20 значений для дальнейшего расчета. Для определения временного промежутка найдем величину $\frac{20}{f_A}$ (подобрана, так как $\frac{10}{f_A}$ демонстрирует некорректную зависимость):

In [5]:
t_range=20/f
t_range

418.4100418410042

В соответствии со второй лабораторной и рассчитанной величиной вводим начальные значения и вектор времени:

In [6]:
y0=(3.255,0.9273504273504274,0.01823529411764707222)
t=np.linspace(0,int(t_range),int(t_range)*10)

Интегрирование системы с определением минимальных и максимальных значений интенсивности

In [7]:
I_min=np.empty(20)
I_max=np.empty(20)
for i in range(len(f_array)):
    solution_ivp=solve_ivp(odes,t_span=[0,max(t)], t_eval=t, y0=y0, args=(B,f_array[i]), rtol=1e-8)
    #print(i)
    print(solution_ivp.y[0])
    print(max(solution_ivp.y[0]))
    #print(min(solution_ivp.y[0]))
    I_min[i]=min(solution_ivp.y[0])
    I_max[i]=max(solution_ivp.y[0])

[3.255      3.25278498 3.2466663  ... 2.1582652  2.15875548 2.15924581]
3.255
[3.255      3.25278499 3.24666642 ... 2.4748056  2.47521992 2.47563071]
3.255
[3.255      3.252785   3.24666653 ... 2.40027462 2.39902988 2.39777919]
3.255
[3.255      3.25278501 3.24666664 ... 2.02140788 2.01924659 2.01709192]
3.255
[3.255      3.25278501 3.24666676 ... 1.80192632 1.80206768 1.80223772]
3.255
[3.255      3.25278502 3.24666687 ... 2.05674964 2.06108652 2.06543973]
3.255
[3.255      3.25278503 3.24666698 ... 2.53854812 2.54155178 2.54447263]
3.255
[3.255      3.25278504 3.2466671  ... 2.54051653 2.53582102 2.53106908]
3.255
[3.255      3.25278504 3.24666721 ... 2.07403335 2.06734366 2.06070459]
3.255
[3.255      3.25278505 3.24666733 ... 1.6906703  1.68847442 1.68639109]
3.255
[3.255      3.25278506 3.24666744 ... 1.72258848 1.7290729  1.73571242]
3.255
[3.255      3.25278506 3.24666755 ... 2.24092217 2.2565125  2.27217119]
3.255
[3.255      3.25278507 3.24666767 ... 2.94161808 2.95577757 2.96

Переход к частотам в ГГц

In [8]:
f_axis=f_array/(tau_p*10**9)

График

In [1]:
%matplotlib widget
plt.figure(1)
plt.title('Зависимость интенсивности от частоты модуляции')
plt.xlabel('f, ГГц')
plt.ylabel('I(f), произв. ед.') 
plt.plot(f_axis, I_min, color='blue', label='$I_{min}$', marker='o')
plt.plot(f_axis, I_max, color='red', label='$I_{max}$', marker='o')
plt.legend(loc='best')
plt.grid()
plt.savefig('graph1FINAL.png',dpi=600)
plt.show()

NameError: name 'plt' is not defined